export const histories: Histories = [
  {
    id: 1,
    name: 'Tambal Ban John',
    createdAt: '8 Apr. 20:10',
    status: 'ONPROGRESS',
    rating: null,
    review: null,
    expired: false,
  },
  {
    id: 2,
    name: 'Tambal Ban John',
    createdAt: '8 Apr. 20:10',
    status: 'COMPLETED',
    rating: 5,
    review: 'Mantep',
    expired: false,
  },
  {
    id: 3,
    name: 'Tambal Ban John',
    createdAt: '8 Apr. 20:10',
    status: 'COMPLETED',
    rating: 5,
    review: null,
    expired: false,
  },
  {
    id: 4,
    name: 'Tambal Ban John',
    createdAt: '8 Apr. 20:10',
    status: 'COMPLETED',
    rating: 5,
    review: null,
    expired: true,
  },
  {
    id: 5,
    name: 'Tambal Ban John',
    createdAt: '8 Apr. 20:10',
    status: 'COMPLETED',
    rating: null,
    review: null,
    expired: false,
  },
  {
    id: 6,
    name: 'Tambal Ban John',
    createdAt: '8 Apr. 20:10',
    status: 'CANCELLED',
    rating: null,
    review: null,
    expired: false,
  },
]
